# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4b1503052d4e7e19ae4a67084acc6302fe4b57100111fccdce6be9bfdbff432af700d82d00c36fcb74cf80e09e5dee1426ca55778ae4d5de335f974ce761ea7

test:
  secret_key_base: 7659779cea1ab2f9c4d0f03096c1d5fdb161ada2cb23c76c30c5c727ef1a58781f23d9bb53c414a76c2b099f1fe27e1c77ef599920e08310ebb4eb7661e9ffeb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
